### ISSUE TITLE
Structure for Toychain instances

### ISSUE THREAD

**Issue by palmskog** [certichain/toychain#11]
Currently, key functions and properties are naked global `Parameter` and `Axiom` declarations. This makes it inconvenient to create multiple instances of Toychain for different applications, and check that they fulfill all (or most) of the requirements. Ideally, there would be a mathcomp-style type with a convenient mixin for this purpose. My current minimum-effort workaround is to define a [functor](https://github.com/certichain/toychain/tree/instantiable), which does not fit well with the general project organization.

**Comment by dranov** [comment]
Has been done as part of the extraction project. Closing old issue.
