### ISSUE TITLE
Toychain as a library

### ISSUE THREAD

**Issue by palmskog** [certichain/toychain#12]
Once there is some way to create [instances](https://github.com/certichain/toychain/issues/11) of Toychain (e.g., Bitcoin, Ethereum), it may be worthwhile to package Toychain as a library others can depend on, and even submit an OPAM package to the Coq OPAM repository. This would reasonably require that the HTT library is packaged properly [as well](https://github.com/certichain/toychain/issues/10).

**Comment by dranov** [comment]
This has been done. Closing old issue.
