### ISSUE TITLE
Weakening hash function injectivity property

### ISSUE THREAD

**Issue by palmskog** [certichain/toychain#13]
Generally, we can't prove general injectivity of the hash functions used in current cryptocurrencies. This makes it impossible to fully instantiate Toychain for e.g., Bitcoin and Ethereum. However, there may be some way to weaken the injectivity requirements to something along the lines of "absence of collisions" and retain currently proved network invariants.

**Comment by dranov** [comment]
See https://github.com/certichain/toychain/pull/21
