### ISSUE TITLE
Fixing compilation with coq/mathComp dev

### ISSUE THREAD

**Issue by germanD** [certichain/toychain#28]
Hi folks!

Happy new year! 

I've just noticed toychain does not compile with dev mathcomp (and coq dev, but changes are from ssreflect path's library). It is a very quick fix ( https://github.com/germanD/toychain/commit/935b73dab66ef6304252cd2a307e769b37ee7bddl). Shall I open a MR? Or you are planning updates in the future?

**Comment by dranov** [comment]
Happy new year to you too!

Thanks for flagging this. Yes, do feel free to open a pull request.
