### ISSUE TITLE
Address vs. nid types

### ISSUE THREAD

**Issue by palmskog** [certichain/toychain#3]
The `Address` and `nid` types are both defined as aliases of `nat`. This is fine as far as it goes, but they seem also to be used as if they always are in fact the same type. For example, we have 
```coq
Parameter genProof : Address -> Blockchain -> option VProof.
```
But the `genProof` function is then used in the `procInt` function as follows:
```coq
let: attempt := genProof n bc in
```
where `n` is nominally of type `nid`.

Wouldn't it make more sense to let `Address` be an arbitrary `Type`, `eqType`, or `ordType`? That `Address` and `nid` are really the same type here seems accidental and restrictive for anyone implementing `genProof`. Another solution that at least makes things clearer is to explicitly assign `nid` to be `Address` or eliminate `nid` altogether.

**Comment by ilyasergey** [comment]
Yes, it all makes sense. A pull request for `eqType` instead of `nat` would be very welcome.

**Comment by palmskog** [comment]
I looked a bit closer at this now, and the problem with simply switching addresses and nids to `eqType` is the following in `States.v`:
```coq
Definition StateMap := union_map [ordType of nid] State.
Fixpoint initState' n : StateMap := if n is n'.+1 then (n \\-> Init n) \+ (initState' n') else Unit.
```

What appears to be needed for a fully satisfactory solution is to make `Address` both an `ordType` (to be able to use `union_map`) and a `finType` (to be able to initialize states for all nodes). Then, one has to reestablish the necessary lemmas, e.g., `initStateValidDom`.

This is above my bandwidth threshold for the moment, but maybe I can look into it in the near future. In the meantime, I will submit a simple pull request that simply replaces `nid` with `Address` (which should remove the confusion I had when reading the source).
